### ISSUE TITLE
Users can delete an entire collection

### ISSUE THREAD

**Issue by IssacL891** [IssacL891/CSCI-320-Final-Project#13]
~TODO: Delete all games from the relation table as well.~

**Comment by dbo8671** [comment]
Delete causes a foreign key error.
 PreparedStatementCallback; SQL [DELETE FROM collection WHERE collectionid = ?;]; ERROR: update or delete on table "collection" violates foreign key constraint "game_in_collection_collection_collectionid_fk" on table "game_in_collection"
  Detail: Key (collectionid)=(211) is still referenced from table "game_in_collection".
