### ISSUE TITLE
Data [Tracker]

### ISSUE THREAD

**Issue by IssacL891** [IssacL891/CSCI-320-Final-Project#18]
Requirements:

- [x] #19
- [x] #20
- [x] #21
- [x] #22
- [x] #23
- [x] #24
- [x] #25
- [x] #26
- [x] #27
- [x] #28
- [x] #29

**Comment by Yiroh** [comment]
For #24, #26, and #27 just need somebody with the know how to insert the data into the database. Don't forget to log the SQL somewhere...

**Comment by Yiroh** [comment]
Inserted all the data into the database, if somebody could quickly go verify and make sure that all the data is there, it all looks good and in the correct columns...
