### ISSUE TITLE
game_in_collection

### ISSUE THREAD

**Issue by IssacL891** [IssacL891/CSCI-320-Final-Project#23]

**Comment by Yiroh** [comment]
@IssacL891 So for this one, are we not letting users just build their own collections? I know we discussed a default collection but unsure how it'd work...

**Comment by Yiroh** [comment]
Same thing with #19 and #28 I believe?

**Comment by Yiroh** [comment]
Scratch the two comments above, #28 has been populated and this issue (#23) will have to be populated too.
