### ISSUE TITLE
Fix hang on exit

### ISSUE THREAD

**Issue by IssacL891** [IssacL891/CSCI-320-Final-Project#30]
Currently, when exiting the application, it hangs due to most likely an issue with Jsch closing the session. After exiting, will hold the port past application lifetime.

### Workarounds:
Use the Logout function to properly logout.

### Quick Fixes:

Find the pid of the application binded to the port 3307 and kill it.

For mac/linux:

> sudo lsof -i -P | grep LISTEN | grep :3307; kill {PID}

For Windows:
!NOT TESTED!
> netstat -ano | findStr "3307"; taskkill /PID {pid}

**Comment by dbo8671** [comment]
resolved
