### ISSUE TITLE
Collection Details

### ISSUE THREAD

**Issue by dbo8671** [IssacL891/CSCI-320-Final-Project#42]
Users will be to see the list of all their collections by name in ascending order. The list
must show the following information per collection:
– Collection’s name
– Number of video games in the collection
– Total play time of the video games (in hours:minutes) of video games in the
collection.

Currently collection list only displays the name

**Comment by Yiroh** [comment]
Now shows collection name, # of video games inside collection, and total play time of collection's contents.
