### ISSUE TITLE
user_plays_game is not 3NF

### ISSUE THREAD

**Issue by IssacL891** [IssacL891/CSCI-320-Final-Project#43]
There is no way to produce a true unrepeating primary key for this relation. (date, userid, gameid, hour, minutes) A user (userid) can play the same game (gameid) on the same day (date) for the same amount of time (hour, minutes).

**Comment by Yiroh** [comment]
Think we fixed this, deciding that the primary key is (date, userid, gameid) and that the hour + minutes aggregates based on the date... No idea if it actually works that way so I won't close it.

UPDATE: The aggregate itself doesn't work, it'll throw errors.

**Comment by dbo8671** [comment]
is it not possible to record the exact time you start playing? like 11/03/32 11:28:56 , its not possible to play the same game concurrently right? So when a user wants to play a game, you just ask them how long, and the start time is automatically generated
