### ISSUE TITLE
Default Collection - Time adding to zero-game collections

### ISSUE THREAD

**Issue by Yiroh** [IssacL891/CSCI-320-Final-Project#44]
So the default collection on a user updates the time up even if there are no games added to their default collection.

Process:
> Before
![image](https://github.com/IssacL891/CSCI-320-Final-Project/assets/69987911/f6d3b32d-71a0-477b-be8a-c678d9b7a941)

Run the 'game play' command on any other collection's game

> After
![image](https://github.com/IssacL891/CSCI-320-Final-Project/assets/69987911/c2f0d361-1303-4ca0-bd84-08eb762b0ece)

As you can see... all the game's times are just adding up over and over whenever you do one "game play" command. By a greater amount than what you say you have played the game for.

**Comment by IssacL891** [comment]
Hm is it because the game is in multiple collections? Like the same game is in more than 1 collection causing the time to aggregate for both?
